In [ ]:
import pandas as pd
from sqlalchemy import create_engine

# Ler points

In [39]:
engine = create_engine('postgresql+psycopg2://postgres:postgres@localhost:5432/postgres')
table_name = "points"
schema = "ndvi"
talhao = "PL PIVO 10B"

query = f"SELECT * FROM {schema}.{table_name} WHERE talhao = '{talhao}'"

# Executa a consulta e carrega os dados em um DataFrame
points = pd.read_sql(query, con=engine)
points.head()

,id,left,top,right,bottom,centroid_x,centroid_y,talhao
0,1023,-45.700007,-12.655978,-45.699648,-12.656337,-45.699777,-12.656221,PL PIVO 10B
1,1024,-45.700007,-12.656337,-45.699648,-12.656697,-45.699757,-12.656454,PL PIVO 10B
2,1051,-45.699648,-12.655619,-45.699288,-12.655978,-45.699401,-12.655882,PL PIVO 10B
3,1052,-45.699648,-12.655978,-45.699288,-12.656337,-45.699468,-12.656158,PL PIVO 10B
4,1053,-45.699648,-12.656337,-45.699288,-12.656697,-45.699468,-12.656517,PL PIVO 10B

# Ler dados s2

In [40]:
table_name = "ndvi_s2"
schema = "ndvi"
start_date = '2024-12-01'
end_date = '2025-04-06'
query = f"""
SELECT * 
FROM {schema}.{table_name}
WHERE data BETWEEN '{start_date}' AND '{end_date}'
"""

# Executa a consulta e carrega os dados em um DataFrame
df_s2 = pd.read_sql(query, con=engine)
df_s2.head()

     ID   ndvi_s2       data
0  1023  0.141639 2024-12-04
1  1023  0.168863 2024-12-09
2  1023  0.259969 2024-12-14
3  1023  0.195396 2024-12-19
4  1023       NaN 2024-12-24

# Ler dados s1

In [41]:
table_name = "ndvi_s1"
schema = "ndvi"
start_date = '2024-12-01'
end_date = '2025-04-06'
query = f"""
SELECT * 
FROM {schema}.{table_name}
WHERE data BETWEEN '{start_date}' AND '{end_date}'
"""

# Executa a consulta e carrega os dados em um DataFrame
df_s1 = pd.read_sql(query, con=engine)
df_s1.head()

     ID     cr_s1       data
0  1023  1.420780 2024-12-08
1  1023  1.451615 2024-12-20
2  1024  1.607798 2024-12-08
3  1024  1.594518 2024-12-20
4  1051  1.170156 2024-12-08

# df predicted

In [44]:
# start df_predicted
df_predicted = points[['id', 'centroid_x', 'centroid_y']]
start_date = '2025-01-01'
end_date = '2025-04-06'


date_range = pd.date_range(start=start_date, end=end_date)

# Expande o DataFrame para incluir todas as combinações de id e datas
df_predicted = df_predicted.merge(
    pd.DataFrame({'data': date_range}),
    how='cross'
)

#julian_day
df_predicted['julian_day'] = df_predicted['data'].dt.dayofyear

#cr_s1
# Renomeia a coluna 'ID' em df_s1 para 'id' para facilitar o merge
df_s1.rename(columns={'ID': 'id'}, inplace=True)
df_s1 = df_s1.sort_values(by=['id', 'data'])

# Faz um merge para combinar os dados de df_predicted com df_s1
df_predicted = df_predicted.merge(
    df_s1[['id', 'data', 'cr_s1']],
    on=['id', 'data'],
    how='left'
)

# Ordena o df_predicted por id e data para garantir a ordem cronológica
df_predicted = df_predicted.sort_values(by=['id', 'data'])
# Preenche os valores ausentes de cr_s1 com o último valor conhecido (forward fill)
df_predicted['lastcr_s1'] = df_predicted.groupby('id')['cr_s1'].fillna(method='ffill')
# Remove a coluna intermediária cr_s1, se necessário
df_predicted.drop(columns=['cr_s1'], inplace=True)
df_predicted.rename(columns={'lastcr_s1': 'cr_s1'}, inplace=True)

#ndvi_s2
# Renomeia a coluna 'ID' em df_s2 para 'id' para facilitar o merge
df_s2.rename(columns={'ID': 'id'}, inplace=True)
# Ordena o DataFrame df_s2 por id e data
df_s2 = df_s2.sort_values(by=['id', 'data'])
# Calcula a média das últimas três ocorrências de ndvi_s2 para cada id
df_s2['rolling_mean_ndvi_s2'] = (
    df_s2.groupby('id')['ndvi_s2']
    .rolling(window=3, min_periods=1)  # Calcula a média das últimas 3 ocorrências
    .mean()
    .reset_index(level=0, drop=True)  # Remove o índice adicional criado pelo rolling
)
# Faz um merge para combinar os dados de df_predicted com df_s2
df_predicted = df_predicted.merge(
    df_s2[['id', 'data', 'rolling_mean_ndvi_s2']],
    on=['id', 'data'],
    how='left'
)
df_predicted['rolling_mean_ndvi_s2'] = df_predicted['rolling_mean_ndvi_s2'].fillna(method='ffill')
df_predicted.rename(columns={'rolling_mean_ndvi_s2': 'ndvi_s2_moving_avg'}, inplace=True)
df_predicted.to_csv('df_predicted.csv', index=False)

C:\Users\sensix\AppData\Local\Temp\ipykernel_2612\3667358187.py:33: FutureWarning: SeriesGroupBy.fillna is deprecated and will be removed in a future version. Use obj.ffill() or obj.bfill() for forward or backward filling instead. If you want to fill with a single value, use Series.fillna instead
  df_predicted['lastcr_s1'] = df_predicted.groupby('id')['cr_s1'].fillna(method='ffill')
C:\Users\sensix\AppData\Local\Temp\ipykernel_2612\3667358187.py:33: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_predicted['lastcr_s1'] = df_predicted.groupby('id')['cr_s1'].fillna(method='ffill')
C:\Users\sensix\AppData\Local\Temp\ipykernel_2612\3667358187.py:56: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_predicted['rolling_mean_ndvi_s2'] = df_predicted['rolling_mean_ndvi_s2'].fillna(method='ffill')

# Rodar modelo

In [45]:
import joblib
# Carrega o modelo, transformador polinomial e scaler
model = joblib.load(r"C:\Users\sensix\Desktop\TESTE_SRICPT\TESTE_SRICPT\SCRIPT_NDVI_PREDICTION\ndvi_prediction_sentinel_123\step_two\regression_model.pkl")
poly = joblib.load(r"C:\Users\sensix\Desktop\TESTE_SRICPT\TESTE_SRICPT\SCRIPT_NDVI_PREDICTION\ndvi_prediction_sentinel_123\step_two\polynomial_features.pkl")
scaler = joblib.load(r"C:\Users\sensix\Desktop\TESTE_SRICPT\TESTE_SRICPT\SCRIPT_NDVI_PREDICTION\ndvi_prediction_sentinel_123\step_two\scaler.pkl")

In [ ]:
# Prepara os dados para previsão
df_features = df_predicted[['cr_s1', 'julian_day', 'ndvi_s2_moving_avg']].copy()
df_features.fillna(0, inplace=True)
df_features.dropna(inplace=True)
# Padroniza os dados
new_X_scaled = scaler.transform(df_features)

# Aplica a transformação polinomial
new_X_poly = poly.transform(new_X_scaled)

# Faz previsões
new_predictions = model.predict(new_X_poly)
df_predicted['ndvi_prediction'] = new_predictions

# Carregar pro banco os valores preditos

In [47]:
engine = create_engine('postgresql+psycopg2://postgres:postgres@localhost:5432/postgres')

def load_to_sql_server(engine, df, table_name, schema="ndvi", max_rows=16384):
    partes = [df[i:i + max_rows] for i in range(0, len(df), max_rows)]
    
    for parte in partes:
        parte.to_sql(name=table_name, con=engine, schema=schema, if_exists="append", index=False)

# Carrega os dados para o SQL Server local
load_to_sql_server(engine, df_predicted, "ndvi_prediction")