##  Bibliotecas:

In [1]:
import geopandas as gpd
import ee
import pandas as pd
import json
import ast
from shapely.geometry import Polygon, MultiPolygon, Point
from sqlalchemy import create_engine

##  Autenticação API:

In [2]:
ee.Authenticate()

# Ligar API GEE
ee.Initialize()

## Shape de Pontos:

In [3]:
#Ler shape de Contornos 
contour_path = (r"C:\Users\sensix\Desktop\TESTE_SRICPT\TESTE_SRICPT\SCRIPT_NDVI_PREDICTION\ndvi_prediction_sentinel_123\fields\PL_PIVO_10B.geojson")
poligonos = gpd.read_file(contour_path)

#Ler shape de points
points_path = (r"C:\Users\sensix\Desktop\TESTE_SRICPT\TESTE_SRICPT\SCRIPT_NDVI_PREDICTION\ndvi_prediction_sentinel_123\fields\POINTS_PL_PIVO_10B.geojson")
points = gpd.read_file(points_path)

roi = ee.FeatureCollection(poligonos.__geo_interface__)

## SENTINEL-2:

In [65]:
start_date = '2024-01-01'  # Data inicial
end_date = '2024-12-31' 

# Função para mascarar nuvens usando a banda MSK_CLDPRB
def mask_clouds(image):
    cloud_prob = image.select('MSK_CLDPRB')
    cloud_mask = cloud_prob.lt(20)  # Máscara para probabilidade de nuvem menor que 20%
    return image.updateMask(cloud_mask)

#Armazena as informações das Bandas por Poligono
df_final = pd.DataFrame()

# loop que abre uma feição por vez
for index, row in points.iterrows():
    polygon = row['geometry'] 
    

    # Verificar o tipo de geometria e converter para o formato do GEE
    if isinstance(row['geometry'], MultiPolygon):
        poligonos_ee = ee.Geometry.MultiPolygon(
            [list(polygon.exterior.coords) for polygon in row['geometry'].geoms]
        )
    elif isinstance(row['geometry'], Polygon):
        poligonos_ee = ee.Geometry.Polygon(
            list(row['geometry'].exterior.coords)
        )
    else:
        raise TypeError("Tipo de geometria não suportado: {}".format(type(row['geometry'])))
    print
   
    # Carregar imagens do satélite Sentinel-2
    s2 = (ee.ImageCollection('COPERNICUS/S2_SR_HARMONIZED')
             .filterDate(start_date, end_date)
             .filterBounds(roi)
             .map(mask_clouds)
             .map(lambda img: img.normalizedDifference(['B8', 'B4']).rename('NDVI')))
       
    # Função para Calcular a média de cada banda 
    def calculateMean(image):
        mean = image.reduceRegions(
            collection=poligonos_ee,
            reducer=ee.Reducer.mean(),
            scale=10
        )
        return mean

    #media das bandas 
    mean = s2.map(calculateMean).flatten()

    # Converter o resultado em um dataframe
    resultados = mean.getInfo()
    data = []
    for feature in resultados['features']:
        properties = feature['properties']
        properties['cena'] = feature['id']
        properties['ID'] = row['id']
        data.append(properties)

        dataframe = pd.DataFrame(data)
        df_final = pd.concat([df_final, dataframe])

# ETL - Transformação e Limpeza dos dados Sentinel-2
dados = df_final[['cena','ID', 'mean']]
dados['data'] = dados['cena'].str[:8]
dados['data'] = pd.to_datetime(dados['data'], format='%Y%m%d')
dados = dados.drop_duplicates(subset=['ID', 'data'])
dados = dados.drop('cena', axis =1)
dados = dados.rename(columns={'mean': 'ndvi_s2'})
dados['ndvi_s2'] = dados['ndvi_s2'].astype(float)
dados

       ID   ndvi_s2       data
0    1023       NaN 2024-01-04
1    1023       NaN 2024-01-09
2    1023  0.298195 2024-01-14
3    1023  0.201421 2024-01-19
4    1023       NaN 2024-01-24
..    ...       ...        ...
67  10914  0.101609 2024-12-09
68  10914  0.189896 2024-12-14
70  10914  0.128669 2024-12-19
71  10914       NaN 2024-12-24
72  10914  0.176048 2024-12-29

[39384 rows x 3 columns]

In [66]:
engine = create_engine('postgresql+psycopg2://postgres:postgres@localhost:5432/postgres')

def load_to_sql_server(engine, df, table_name, schema="ndvi", max_rows=16384):
    partes = [df[i:i + max_rows] for i in range(0, len(df), max_rows)]
    
    for parte in partes:
        parte.to_sql(name=table_name, con=engine, schema=schema, if_exists="append", index=False)

# Carrega os dados para o SQL Server local
load_to_sql_server(engine, dados, "ndvi_s2")

## SENTINEL-1

In [92]:
start_date = '2024-01-01'  # Data inicial
end_date = '2024-12-31' 

#Armazena as informações das Bandas por Poligono
df_final = pd.DataFrame()

# loop que abre uma feição por vez
for index, row in points.iterrows():
    polygon = row['geometry'] 
    

    # Verificar o tipo de geometria e converter para o formato do GEE
    if isinstance(row['geometry'], MultiPolygon):
        poligonos_ee = ee.Geometry.MultiPolygon(
            [list(polygon.exterior.coords) for polygon in row['geometry'].geoms]
        )
    elif isinstance(row['geometry'], Polygon):
        poligonos_ee = ee.Geometry.Polygon(
            list(row['geometry'].exterior.coords)
        )
    else:
        raise TypeError("Tipo de geometria não suportado: {}".format(type(row['geometry'])))
    print
   
    # Carregar imagens do satélite Sentinel-2
    s1 = (ee.ImageCollection('COPERNICUS/S1_GRD')
         .filterDate(start_date, end_date)
         .filterBounds(roi)
         .map(lambda img: img.select(['VH', 'VV']).addBands(
             img.select('VH').divide(img.select('VV')).rename('VH_div_VV')
         )))
       
    # Função para Calcular a média de cada banda 
    def calculateMean(image):
        mean = image.reduceRegions(
            collection=poligonos_ee,
            reducer=ee.Reducer.mean(),
            scale=10
        )
        return mean

    #media das bandas 
    mean = s1.map(calculateMean).flatten()

    # Converter o resultado em um dataframe
    resultados = mean.getInfo()
    data = []
    for feature in resultados['features']:
        properties = feature['properties']
        properties['cena'] = feature['id']
        properties['ID'] = row['id']
        data.append(properties)

        dataframe = pd.DataFrame(data)
        df_final = pd.concat([df_final, dataframe])

# ETL - Transformação e Limpeza dos dados Sentinel-2
dados = df_final[['cena','ID', 'VH_div_VV']]
dados['data'] = dados['cena'].str[17:25]
dados['data'] = pd.to_datetime(dados['data'], format='%Y%m%d')
dados = dados.drop_duplicates(subset=['ID', 'data'])
dados = dados.drop('cena', axis =1)
dados = dados.rename(columns={'VH_div_VV': 'cr_s1'})
dados['cr_s1'] = dados['cr_s1'].astype(float)
dados

C:\Users\sensix\AppData\Local\Temp\ipykernel_21372\2990158267.py:55: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  df_final = pd.concat([df_final, dataframe])
C:\Users\sensix\AppData\Local\Temp\ipykernel_21372\2990158267.py:59: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['data'] = dados['cena'].str[17:25]
C:\Users\sensix\AppData\Local\Temp\ipykernel_21372\2990158267.py:60: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dados['data'] = pd.to_datetime(dados['data'], format='%Y%m%d')

       ID     cr_s1       data
0    1023  1.323236 2024-01-07
1    1023  1.607269 2024-01-19
2    1023  1.363743 2024-01-31
3    1023  1.601639 2024-02-12
4    1023  1.938773 2024-02-24
..    ...       ...        ...
25  10914  2.227045 2024-11-02
26  10914  1.425688 2024-11-14
27  10914  2.265401 2024-11-26
28  10914  2.148668 2024-12-08
29  10914  2.627005 2024-12-20

[16410 rows x 3 columns]

In [93]:
engine = create_engine('postgresql+psycopg2://postgres:postgres@localhost:5432/postgres')

def load_to_sql_server(engine, df, table_name, schema="ndvi", max_rows=16384):
    partes = [df[i:i + max_rows] for i in range(0, len(df), max_rows)]
    
    for parte in partes:
        parte.to_sql(name=table_name, con=engine, schema=schema, if_exists="append", index=False)

# Carrega os dados para o SQL Server local
load_to_sql_server(engine, dados, "ndvi_s1")